//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `MP3Manager.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let AppServer = _ModuleRegistry.module("AppServer");

    const iceC_AppServer_Track_ids = [
        "::AppServer::Track",
        "::Ice::Object"
    ];

    AppServer.Track = class extends Ice.Value
    {
        constructor(id = "", title = "", artist = "", album = "", path = "")
        {
            super();
            this.id = id;
            this.title = title;
            this.artist = artist;
            this.album = album;
            this.path = path;
        }

        _iceWriteMemberImpl(ostr)
        {
            ostr.writeString(this.id);
            ostr.writeString(this.title);
            ostr.writeString(this.artist);
            ostr.writeString(this.album);
            ostr.writeString(this.path);
        }

        _iceReadMemberImpl(istr)
        {
            this.id = istr.readString();
            this.title = istr.readString();
            this.artist = istr.readString();
            this.album = istr.readString();
            this.path = istr.readString();
        }
    };

    Slice.defineValue(AppServer.Track, iceC_AppServer_Track_ids[0], false);

    const iceC_AppServer_MP3Manager_ids = [
        "::AppServer::MP3Manager",
        "::Ice::Object"
    ];

    AppServer.MP3Manager = class extends Ice.Object
    {
    };

    AppServer.MP3ManagerPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(AppServer.MP3Manager, AppServer.MP3ManagerPrx, iceC_AppServer_MP3Manager_ids, 0,
    {
        "add": [, , , , [1], [["AppServer.Track", true]], , , true, ],
        "remove": [, , , , [1], [[7]], , , , ],
        "play": [, , , , [1], [["AppServer.Track", true]], , , true, ],
        "search": [, , , , ["AppServer.Track", true], [[7], [7]], , , , true],
        "getTrackList": [, , , , [7], , , , , ]
    });
    exports.AppServer = AppServer;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
